### ISSUE TITLE
The result is very different from that in the paper

### ISSUE THREAD

**Issue by TingMAC** [hezhangsprinter/DCPDN#28]
I downloaded the pre_trained model and the nature image, and run the command python demo.py --dataroot ./facades/nat_new4 --valDataroot ./facades/nat_new4 --netG ./demo_model/netG_epoch_8.pth, but the obtained results in result_cvpr18 are different from those in the paper. There is obvious haze in the results. If you have time, please tell me how can I solve the problem?

**Comment by hezhangsprinter** [comment]
If you strictly follow the readme.md and do exactly everything same, you should reproduce the results exactly same as in my github and also the paper.  It won't be huge difference if you following everything and use the same image. 

Make sure you are using net.train() rather than net.eval(). 

If you want to reproduce the table results, please using the demo.py to generate the target image and  then do the comparison using SSIM.   


Let me know if you have further concerns.

**Comment by TingMAC** [comment]
Thank you. I have reproduce the results.

**Comment by TingMAC** [comment]
Another question. If the image is not 256*256 or 512*512, there will be an error message：‘’invalid argument 0: Sizes of tensors must match except in dimension 1. Got 3 and 2 in dimension 2 at /opt/conda/conda-bld/pytorch_1525796793591/work/torch/lib/THC/generic/THCTensorMath.cu:111‘’.
Is there a way to run the code with input hazy image of any arbitrary size？
